### ISSUE TITLE
0.2.0: TimeoutError on recv()

### ISSUE THREAD

**Issue by contyk** [contyk/mlck#2]
Not entirely sure how this can happen but apparently it can -- mlck crashed on connection timeout while handling `recv()`.

```
Traceback (most recent call last):
  File "./mlck", line 3034, in <module>
    main()
  File "./mlck", line 3031, in main
    handle(k, m)
  File "./mlck", line 2887, in handle
    recv = sock.recv(config['buffer'])
TimeoutError: [Errno 110] Connection timed out
```

So the selector indicates there's something to read (the mask matches `selectors.EVENT_READ`) but then... we can't read it? Or can't read it in full? Possibly an incomplete message on the TCP level?

`socket` documentation is not the best and doesn't document all the exceptions it raises. I'm also unsure how to handle this one. Should I destroy the session, close and unregister the connection? Probably.

**Comment by contyk** [comment]
I'll experiment with handling just `socket.herror` everywhere.
